# Generated by Django 5.1.3 on 2024-11-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='process_backend_id',
            field=models.CharField(default='', help_text='Уникальный идентификатор процесса, созданный на бэкенде', max_length=254, unique=True, verbose_name='id процесса'),
        ),
    ]
