# Generated by Django 5.1.3 on 2024-11-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_process_serverconfig_remove_task_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='anser',
            new_name='answer',
        ),
    ]
